config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  root 'home#index'

  post 'feedback' => 'home#feedback'

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get  :result
      post :gist
    end
  end

  resources :badges, only: :index
  resources :user_badges, only: :index

  namespace :admin do
    root 'tests#index'
    
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, :last_name, presence: true 
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :answers_count, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def answers_count
    errors.add(:answer, 'number is too much') if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  enum rule: { category_complete: 0, level_complete: 1, first_attempt: 2, second_attempt: 3 }

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  before_save :set_image, on: :create

  validates :name, uniqueness: true

  private

  def set_image
    self.image = 'badge.png'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true, uniqueness: true 

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: :current_question_id
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :category

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, numericality: { only_integer: true }
  validates :level, uniqueness: { scope: :title }

  scope :simple, -> { where('level IN (?)', [0, 1]) }
  scope :middle, -> { where('level IN (?)', (2..4)) }
  scope :complicated, -> { where('level >= ?', 5) }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_THRESHOLD = 0.85.freeze

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, if: :new_record?
  before_save :before_save_set_next_question, unless: :new_record?
  before_save :before_save_check_success, unless: :new_record?

  def accept!(answer_ids)
    self.correct_questions += 1 if answer_ids.present? && correct_answer?(answer_ids)
    save
  end

  def completed?
    current_question.nil?
  end

  def result
    correct_questions.to_f/test.questions.count
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.order(:id).first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_save_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_save_check_success
    self.success = result >= SUCCESS_THRESHOLD
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :test
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable


  enum role: %i[admin regular]

  has_many :authored_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  def tests_by_level(level)
    self.tests.where(level: level)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge).permit(:name, :rule)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in? && current_user.sign_in_count == 1
      flash.now[:notice] = "Привет, #{current_user.email}!"
    end
  end

  def feedback
    FeedbacksMailer.send_feedback(feedback_params).deliver

    redirect_to root_path
  end

  private

  def feedback_params
    params.permit(:name, :email, :body)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test, only: :start

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to test_passage_path(current_user.test_passage(@test))
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_header(answer)
    if answer.new_record?
      "Новый ответ на вопрос: #{answer.question.body}"
    else
      "Редактировать ответ на вопрос: #{answer.question.body}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def footer_year
    Time.zone.now.year
  end

  def github_url(author, repo)
    link_to author, repo, target: "_blank"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Новый вопрос по #{question.test.title}"
    else
      "Редактировать вопрос по #{question.test.title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def show_alert
    if flash[:alert]
      content_tag :p, flash[:alert], class: 'flash alert'
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def show_score
    content_tag :h3, @test_passage.correct_questions, class: "result-#{result_type}"
  end

  def show_message
    content_tag :p, "#{result_type == 'success' ? t('test_passages.result.success') : t('test_passages.result.fail')}"
  end

  def show_badge
    if @badge
      image_tag @badge.image, class: 'badge-img'
    end
  end

  private

  def result_type
    @result >= 0.85 ? 'success' : 'fail'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.id %></td>
  <td><%= image_tag badge.image, class: "admin-badge-img" %></td>
  <td><%= badge.name %></td>
  <td><%= badge.rule %></td>
  <td>
    <%= link_to t('buttons.edit'), edit_admin_badge_path(badge), class: "btn btn-warning" %>
  </td>
  <td>
    <%= link_to t('buttons.delete'), admin_badge_path(badge), method: :delete, data: { confirm: t('confirmations.sure') }, class: "btn btn-danger" %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <div class="form-group">
    <%= render 'shared/errors', resource: @badge %>

    <%= form.label :name %>
    <%= form.text_field :name, id: :name, class: "form-control mb-3" %>

    <p>
      <%= form.select :rule, options_for_select(Badge.rules.keys), class: "form-control" %>
    </p>

    <%= form.submit t('buttons.submit'), class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/admin/badges/edit.html.erb
<div class="row justify-content-center">
  <div class="col col-md-4">
    <h4 align="center"><%= t('badges.edit.header', badge_name: @badge.name) %></h4>

    <%= render 'form' %>
    <%= link_to t('buttons.back'), admin_badges_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center">
  <div class="col">

    <div class="test-header">
      <h1><%= t('badges.index.header') %></h1>
      <%= link_to t('badges.new.header'), new_admin_badge_path, class: "btn btn-primary m-3" %>
    </div>

    <%= render 'shared/errors', resource: @badge  %>

    <table class="table table-hover">
      <thead>
      <tr>
        <th>ID</th>
        <th></th>
        <th><%= t('activerecord.attributes.badge.name') %></th>
        <th><%= t('activerecord.attributes.badge.rule') %></th>
        <th colspan="2"><%= t('actions') %></th>
      </tr>
      </thead>
      <tbody>
      <%= render @badges %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/badges/new.html.erb
<div class="row justify-content-center">
  <div class="col col-md-4">
    <h4 align="center"><%= t('badges.new.header') %></h4>

    <%= render 'form' %>
    <%= link_to t('buttons.back'), admin_badges_path, class: "btn btn-primary mb-3" %>
  </div>
</div>

app/views/badges/_badge.html.erb
<tr>
  <td><%= badge.id %></td>
  <td><%= badge.name %></td>
  <td><%= badge.rule %></td>
</tr>

app/views/badges/index.html.erb
<div class="row justify-content-center">
  <div class="col">
    <h1 align="center"><%= t('badges.index.header') %></h1>

    <table class="table table-hover">
      <thead>
      <tr>
        <th>ID</th>
        <th><%= t('activerecord.attributes.badge.name') %></th>
        <th><%= t('activerecord.attributes.badge.rule') %></th>
      </tr>
      </thead>
      <tbody>
      <%= render @badges %>
      </tbody>
    </table>
  </div>
</div>