config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  root 'home#index'

  post 'feedback' => 'home#feedback'

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get  :result
      post :gist
    end
  end

  resources :badges, only: :index
  resources :user_badges, only: :index

  namespace :admin do
    root 'tests#index'
    
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: :current_question_id
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_THRESHOLD = 0.85.freeze

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, if: :new_record?
  before_save :before_save_set_next_question, unless: :new_record?
  before_save :before_save_check_success, unless: :new_record?

  def accept!(answer_ids)
    self.correct_questions += 1 if answer_ids.present? && correct_answer?(answer_ids)
    save
  end

  def completed?
    current_question.nil?
  end

  def result
    correct_questions.to_f/test.questions.count
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.order(:id).first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_save_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_save_check_success
    self.success = result >= SUCCESS_THRESHOLD
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]
  before_action :set_current_question_number, only: :show

  def show
  end

  def result
    @result = @test_passage.result
    @badge  = SetBadgeService.new(test_passage: @test_passage).call if @test_passage.success
    TestsMailer.completed_test(@test_passage).deliver_now
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      redirect_to result_test_passage_path(@test_passage)
    else
      redirect_to test_passage_path(@test_passage)
    end
  end

  def gist
    service = GistQuestionService.new(@test_passage.current_question)
    result = service.call

    flash_options = if service.success?
                      create_gist(result[:html_url])
                      { notice: t('.success', url: result[:html_url]) }
                    else
                      { alert: t('.failure') }
                    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def set_current_question_number
    @number = @test_passage.test.questions.order(:id).index(@test_passage.current_question) + 1
  end

  def create_gist(url)
    current_user.gists.create(url: url, question: @test_passage.current_question)
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def show_score
    content_tag :h3, @test_passage.correct_questions, class: "result-#{result_type}"
  end

  def show_message
    content_tag :p, "#{result_type == 'success' ? t('test_passages.result.success') : t('test_passages.result.fail')}"
  end

  def show_badge
    if @badge
      image_tag @badge.image, class: 'badge-img'
    end
  end

  private

  def result_type
    @result >= 0.85 ? 'success' : 'fail'
  end
end

app/views/test_passages/result.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col col-md-4">
      <h1><%= @test_passage.test.title %></h1>

      <%= show_score %>
      <%= show_message %>
      <%= show_badge %>

      <p><%= link_to t('buttons.all_tests'), tests_path %></p>
    </div>
  </div>
</div>

app/views/test_passages/show.html.erb
<div class="container">
  <h3 class="timer" id="timer" data-id=<%= @test_passage.test.id %> data-duration=<%= @test_passage.test.duration %> >
  </h3>
  <div class="row justify-content-center">
    <div class="">
      <h1 align="center"><%= "#{t('test_passages.show.header')} #{@test_passage.test.title}" %></h1>

      <p>
        <%= "#{t('test_passages.show.question')}: #{@number}/#{@test_passage.test.questions.count}" %>
      </p>

      <b>
        <%= @test_passage.current_question.body %>
      </b>

      <%= form_with url: test_passage_path(@test_passage), locale: true, method: :put do |form| %>
        <div class="form-group">
          <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
            <p>
              <%= b.check_box id: "answer_ids_#{b.object.id}", class: "form-check-input" %>
              <%= b.label class: "form-check-label"%>
            </p>
          <% end %>
          <p><%= link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post, class: "btn btn-notice" %></p>
          <%= form.submit t('buttons.next'), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>

    <%= content_tag :div, class: 'mt-3', id: 'progress-bar', data: { questions_count: @test_passage.test.questions.count, question_number: @number } do %>
      <div id="progress-bar-line"></div>
    <% end %>
  </div>
</div>

<script>
  window.onload = function exampleFunction() {
    setTestTimer()
  }
</script>