config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  root 'home#index'

  post 'feedback' => 'home#feedback'

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get  :result
      post :gist
    end
  end

  resources :badges, only: :index
  resources :user_badges, only: :index

  namespace :admin do
    root 'tests#index'
    
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, :last_name, presence: true 
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :answers_count, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def answers_count
    errors.add(:answer, 'number is too much') if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  enum rule: { category_complete: 0, level_complete: 1, first_attempt: 2, second_attempt: 3 }

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  before_save :set_image, on: :create

  validates :name, uniqueness: true

  private

  def set_image
    self.image = 'badge.png'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true, uniqueness: true 

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: :current_question_id
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :category

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, numericality: { only_integer: true }
  validates :level, uniqueness: { scope: :title }

  scope :simple, -> { where('level IN (?)', [0, 1]) }
  scope :middle, -> { where('level IN (?)', (2..4)) }
  scope :complicated, -> { where('level >= ?', 5) }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_THRESHOLD = 0.85.freeze

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, if: :new_record?
  before_save :before_save_set_next_question, unless: :new_record?
  before_save :before_save_check_success, unless: :new_record?

  def accept!(answer_ids)
    self.correct_questions += 1 if answer_ids.present? && correct_answer?(answer_ids)
    save
  end

  def completed?
    current_question.nil?
  end

  def result
    correct_questions.to_f/test.questions.count
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.order(:id).first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_save_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_save_check_success
    self.success = result >= SUCCESS_THRESHOLD
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :test
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable


  enum role: %i[admin regular]

  has_many :authored_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  def tests_by_level(level)
    self.tests.where(level: level)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in? && current_user.sign_in_count == 1
      flash.now[:notice] = "Привет, #{current_user.email}!"
    end
  end

  def feedback
    FeedbacksMailer.send_feedback(feedback_params).deliver

    redirect_to root_path
  end

  private

  def feedback_params
    params.permit(:name, :email, :body)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test, only: :start

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to test_passage_path(current_user.test_passage(@test))
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_header(answer)
    if answer.new_record?
      "Новый ответ на вопрос: #{answer.question.body}"
    else
      "Редактировать ответ на вопрос: #{answer.question.body}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def footer_year
    Time.zone.now.year
  end

  def github_url(author, repo)
    link_to author, repo, target: "_blank"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Новый вопрос по #{question.test.title}"
    else
      "Редактировать вопрос по #{question.test.title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def show_alert
    if flash[:alert]
      content_tag :p, flash[:alert], class: 'flash alert'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/admin/nav' %>
    <div class="container main">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render 'shared/footer'%>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container main">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render 'shared/feedback_modal' %>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h4>Возникли ошибки:</h4>
    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_feedback_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" aria-hidden="true" id="feedback-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t("feedback.title") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with url: feedback_path, method: :post do |form| %>
          <div class="form-group">
            <%= form.label :name, t("helpers.label.feedback_modal.name") %><br>
            <%= form.text_field :name, class: "form-control mb-3" %>
            <%= form.label :email, t("helpers.label.feedback_modal.email") %><br>
            <%= form.text_field :email, class: "form-control mb-3" %>
            <%= form.label :body, t("helpers.label.feedback_modal.body") %><br>
            <%= form.text_area :body, class: "form-control mb-3" %>

            <%= form.submit text=t("buttons.submit"), class: "btn btn-primary"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <% flash.each do |key, message| %>
      <div class="alert alert-primary" role="alert">
        <%= message %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer" align="center">
  <div class="container">
    <div class="row">
      <div class="col col-12">
        <div>TestGuru © <span><%= footer_year %></span></div>
        <div>Удобный инструмент для создания, управления и прохождения тестов</div>
        <div>Учебный проект в онлайн-школе
          <span><a href="http://thinknetica.com/" target="_blank">Thinknetica</a></span>
        </div>
        <%= github_url('Sophiliya', "https://github.com/Sophiliya/test-guru") %>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Test Guru', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to t('tests.index.header'), tests_path, class: 'btn' %>
      </li>
      <li class="nav-item active">
        <%= link_to t('buttons.feedback'), '', class: 'btn', id: 'feedback-link', data: { toggle: "modal", target: "#feedbackModal" } %>
      </li>
      <li class="nav-item active">
        <%= link_to t('badges.index.header'), badges_path, class: 'btn' %>
      </li>
      <li class="nav-item active">
        <%= link_to t('user_badges.header'), user_badges_path, class: 'btn' %>
      </li>
    </ul>
  </div>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('welcome') %><b><%= current_user.first_name %></b>!
      <%= link_to t('buttons.logout'), destroy_user_session_path, method: :delete, class: 'navbar-link' %>
    <% else %>
      <%= link_to t('buttons.login'), user_session_path %>
      <%= link_to t('buttons.signup'), new_user_registration_path %>
    <% end %>
  </span>
</nav>

app/views/shared/admin/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/admin">Test Guru</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/admin/tests"><%= t('buttons.all_tests') %></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/admin/tests/new"><%= t('buttons.new_test') %></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/admin/gists"><%= t('gists.index.header') %></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/admin/badges"><%= t('badges.index.header') %></a>
      </li>
    </ul>
  </div>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <b><%= current_user.first_name %></b>
      <%= link_to t('buttons.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('buttons.login'), user_session_path %>
      <%= link_to t('buttons.signup'), new_user_registration_path %>
    <% end %>
  </span>
</nav>